apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ex3rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: container1
          image: kuldeeproy/ex3httpd


---

apiVersion: v1
kind: Service
metadata:
  name: ex3service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
